import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import vuePlugin from "esbuild-plugin-vue3";
import { copyFileSync, mkdirSync, existsSync, unlinkSync } from "fs";

const prod = process.argv[2] === "production";

const outDir = "dist/obsidian-autotimestamp";
const pluginDir = "D:/Obsidian/note-gen-sync/.obsidian/plugins/obsidian-autotimestamp";

if (!existsSync(outDir)) {
  mkdirSync(outDir, { recursive: true });
}

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  plugins: [vuePlugin()],
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: `${outDir}/main.js`,
});

function copyAssets() {
  copyFileSync("manifest.json", `${outDir}/manifest.json`);
  copyFileSync("styles.css", `${outDir}/styles.css`);
  
  const extraCss = `${outDir}/main.css`;
  if (existsSync(extraCss)) {
    unlinkSync(extraCss);
  }
  
  console.log("Build complete! Files in", outDir);
  
  if (existsSync(pluginDir)) {
    if (!existsSync(pluginDir)) {
      mkdirSync(pluginDir, { recursive: true });
    }
    copyFileSync(`${outDir}/main.js`, `${pluginDir}/main.js`);
    copyFileSync(`${outDir}/manifest.json`, `${pluginDir}/manifest.json`);
    copyFileSync(`${outDir}/styles.css`, `${pluginDir}/styles.css`);
    console.log("Copied to Obsidian plugin dir:", pluginDir);
  } else {
    console.log("Plugin directory not found, skipping copy:", pluginDir);
  }
}

if (prod) {
  await context.rebuild();
  copyAssets();
  process.exit(0);
} else {
  copyAssets();
  await context.watch();
}
